# 调试模式
debug: false

# 服务器配置
server:
  # 内建HTTP服务器来接收 支付付通知
  port: 8822
  # 异步通知地址 商户付款成功后会通过该地址通知支付结果
  # 可以用IP 请保证可被外网访问
  # 启动服务器后直接访问此地址 有内容显示则表示已正常运行
  # 例: http://<yourIp or yourDomain>:<port>/
  notify: ""

# 商户配置
# 插件需要你的商户信息 创建订单
# 不设置则无法使用该支付方式创建订单
merchant:
  # 支付宝(申请较易,个人可申请)
  # 支付宝商家中心: https://b.alipay.com/
  # 支付宝开放平台: https://open.alipay.com/
  alipay:
    # 启用该支付方式
    enable: true
    # 支付宝开放平台中创建应用的APPID
    app-id: 20************73
    # 支付宝商户平台中交换商户公钥即可获得支付宝公钥
    alipay-public-key: MI****************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************AB
    # 商户私钥 与自己创建的商户公钥对应的商户私钥
    merchant-private-key: MI************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************g=

  # 微信(企业/个体工商户可申请,申请难度一般)
  # 微信商户平台: https://pay.weixin.qq.com/
  # 微信公众平台: https://mp.weixin.qq.com/
  wechat:
    # 启用该支付方式
    enable: true
    # 微信公众平台中创建的公众号/小程序的APPID
    app-id: wx**************e4
    # 微信商户平台中的商户号
    merchant-id: 16******68
    # 在商户平台由自己上传的随机32位私钥
    merchant-key: At****************************3f

  # QQ钱包(企业可申请,申请难度较大)
  # QQ钱包商户平台: https://mp.qpay.tenpay.com/
  tenpay:
    # 启用该支付方式
    enable: false
    # QQ互联平台中创建应用的APPID(非必选)
    app-id: ""
    # QQ钱包商户平台中的商户号
    merchant-id: 16******01
    # 在QQ钱包商户平台中的随机32位私钥
    merchant-key: nq****************************5C

# 存储配置
# 用于存储订单信息
storage:
  # 数据库类型
  # SQLite / MySQL
  type: SQLite
  # 数据库地址
  address: "localhost"
  # 端口号
  port: 3306
  # 数据库名
  database: "payapi"
  # 数据库用户名
  username: "root"
  # 数据库密码
  password: "123456"